```{r}
library(tidyverse)
library(httr)
library(RCurl)
```
- grep(찾는패턴, 찾는대상, value=T, ignore.case=T)
```{r}
string= installed.packages() 
string %>% grep("ak.",.,value=T)
```


```{r}
string %>% grep("(pr){1,3}",.,value=T)
```
- greedy & lazy matching
```{r}
html.doc= "<TITLE>Happly Days</TITLE>"
gsub("<.*>","",html.doc)
gsub("<.*?>","",html.doc) #수량지정자뒤에 ?를 붙힌다.
```

```{r}
gregexpr("<.*?>", html.doc) %>% regmatches(html.doc, .)
```
- 이스케이프 시퀀스
```{r}
string= "I need 100$, She gave me a ^. I don't know why."

gsub("\\^","carrot", string)
```

- 백레퍼런스
```{r}
string= "# a small thing makes a big difference #"
gsub("(\\w).+\\1","*",string)
```

```{r}
html= "<div class='power'>100%</dev>"
regmatches(html,regexpr("\\d+.",html))

gsub("(<.+?>)","",html)

gsub("(<.*?>)(.*)(<.*?>)","\\2",html)
```
```{r}
regmatches(state.name,regexpr("^New(.*[xy].*)",state.name))
```
```{r}
gsub("^New(.*[xy].*)","NEW\\1", state.name) %>% grep("^new",.,ignore.case=T, value=T)
```

```{r}
telephone= "Barabasi, Albert-Laszlo917 1843James Bond(02) 563-1987(1)John F.Kennedy051-776-5879(123)Dr.Who(062) 324-9576McCartney, J.Paul0648323912"
telephone
```
```{r}
names= regmatches(telephone, gregexpr("[[:alpha:] .,-]{2,}",telephone)) %>% unlist(.)
names
```

```{r}
phone= 
  regmatches(telephone, 
             gregexpr("\\(?(\\d{2,3})?\\)?(-| )?\\d{3}(-| )?\\d{4}\\(?(\\d{1,3})?\\)?",
                      telephone)) %>% unlist()
phone
```

```{r}
str_match_all(telephone,
              "\\(?(\\d{2,3})?\\)?(-| )?(\\d{3})(-| )?(\\d{4})\\(?(\\d{1,3})?\\)?") %>% 
  .[[1]] %>% 
  as_tibble(.) %>% 
  #select(V2,V4,V6,V7) %>% 
  transmute(local_no= V2, 
            phone_no= paste0(V4,"-",V6),
            inter_no= V7) %>% 
  replace_na(list(local_no= "*", phone_no="-", inter_no="*")) %>% 
  bind_cols(tibble(names),.)
```

```{r}
ll= system("cat /etc/passwd", intern = T) %>% unlist(.)
ll[str_detect(ll,"cgm")]
```

```{r}
mon= c(1:12)

str_pad(mon, width = 2, side = "left", pad=0)
```

```{r}
str_c(c("data mining","text mining"), "is useful", sep=" ", collapse = "\n") %>% cat()
```

```{r}
ll %>% str_c(collapse = ";")
```

```{r}
Sys.getlocale()
Sys.localeconv()
localeToCharset()
```

```{r}
star="별 헤는 밤"
Encoding(star)= "EUC-KR"
star
```

```{r}
guess_encoding(file="https://www.mk.co.kr")
get= GET(url="https://www.mk.co.kr")
html= content(get, as="text")
```
```{r}
url= "http://www.abrahamlincolnonline.org/lincoln/speeches/gettysburg.htm"
html= getURL(url)
```

```{r}
html %>% 
  str_replace_all(.,"<.*>","") %>% 
  str_replace_all(.,"\\s{1,}"," ") %>%
  str_trim() %>% 
  cat()
```




















































