### 1. loading library

```{r}
library(httr)
library(XML)
library(tidyverse)
```

### 2. parsing html

```{r}
url= "https://www.imdb.com/search/title/?title_type=feature&release_date=2005-01-01,2005-12-31&count=100"
html= GET(url)
html.parsed= htmlParse(html)
```

### 3. 영화 순위 추출

```{r}
rank= 
  xpathSApply(html.parsed,
              "//span[@class='lister-item-index unbold text-primary']",
              xmlValue) %>% 
  parse_number(.)
rank[1:20]
```

### 4. 영화 제목 추출

```{r}
title= 
  xpathSApply(html.parsed,
              "//span[@class='lister-item-index unbold text-primary']
              /following-sibling::a",
              xmlValue)
  
title %>% head(5)
```

### 5. 영화 줄거리 추출

```{r}
story=
  xpathSApply(html.parsed, "//p[@class='text-muted']", xmlValue, trim=T)

story %>% head(5)
```

### 6. 상영시간 추출

```{r}
runtime=
  xpathSApply(html.parsed, "//span[@class='runtime']", xmlValue) %>% 
  parse_number()

runtime %>% head()
```

### 7. 영화 장르 추출

-   여러 장르는 대표적으로 첫 장르를 추출한다.

```{r}
genre=
  xpathSApply(html.parsed, "//span[@class='genre']", xmlValue, trim=T) %>% 
  str_extract("\\w+") %>% 
  as_factor()

genre
```

### 8. 영화 평점 추출

```{r}
rating=
  xpathSApply(html.parsed, "//div[@name='ir']/strong", xmlValue) %>% 
  parse_number()
  
rating %>% head()
```

### 9. 영화 감독 추출

```{r}
director=
  xpathSApply(html.parsed, "//p[@class='']/a[1]", xmlValue)

director %>% head()
```

### 10. 투표수 추출

-   노드의 콘텐츠를 추출하는 경우 : xmlValue()

```{r}
vote=
  xpathSApply(html.parsed, "//span[@name='nv'][1]", xmlValue) %>% 
  str_replace_all(.,",","") %>%
  as.numeric(.)

vote[1:10]
```

-   여러 노드가 추출될 때 : [1]로 조건식에 맞는 노드를 찾는다.

```{r}
xpathSApply(html.parsed,
            "//span[contains(text(),'Votes')]/following-sibling::span[1]",
            xmlValue) %>%
  parse_number(.) %>%
  .[1:10]
```

-   노드내의 속성정보를 추출하는 경우 : xmlGetAttr()

```{r}
xpathSApply(html.parsed, "//span[@name='nv'][1]", xmlGetAttr,"data-value") %>% 
  parse_number(.) %>% 
  .[1:10]
```

### 11. 흥행 수익 데이터 추출

-   노드내의 속성정보를 추출한다.

-   총갯수가 95개로 일부정보가 없는 노드가 있다. 추출이후에는 어느 영화가 정보가 없는 영화인지 알 수 없다.

-   xpathSApply()내 function()을 정의해서 사용한다.

```{r}
gross=
  xpathSApply(html.parsed, 
              "//p[@class='sort-num_votes-visible']",
              function(x) {
                val= xpathSApply(x, "./span[5]", xmlGetAttr, "data-value") %>% 
                  unlist(.)
                val= ifelse(is.null(val), NA, val)}) %>% 
  parse_number()

gross[1:10]
```

### 12. 장르별 흥행 수익 비교

```{r}
library(lessR)

d= tibble(
  genre= genre,
  gross= gross)
d
```

```{r}
Plot(gross, by1=genre, vbs_plot = "bs")
```
